### ISSUE TITLE
rename scripts

### ISSUE THREAD

**Issue by wwieder** [hhollandmoritz/NWT_CLM#15]
please make more descriptive.  this will also have to be updated in readme

**Comment by hhollandmoritz** [comment]
I changed the names as follows:

tvan_supplemental_cleaning.R -> clean_tvan_data.R
flow.lter.clm.R -> prepare_forcings_for_clm.R
flow.obs.R -> prepare_obs_for_comparison.R
flow.sim.R -> prepare_sim_for_comparison.R
Obs_sim_comp_plots.R -> plot_obs_sim_comparisons.R

**Comment by hhollandmoritz** [comment]
I still need to update the image in the Readme. I will do this today.

**Comment by hhollandmoritz** [comment]
Image updated.
