### ISSUE TITLE
time shift in CLM

### ISSUE THREAD

**Issue by wwieder** [hhollandmoritz/NWT_CLM#8]
The timing of RNET seems offest. I think this is because of an issue in CLM and how it reads / writes out data. 
Can we shift all CLM results back 1 step (30 minutes) and see if the diel cycle looks better?https://github.com/hhollandmoritz/NWT_CLM/blob/5514b7f1ad8739da459688c67957f142b9713e0e/Obs_sim_comp_plots.R#L80

**Comment by wwieder** [comment]
this should be in flow_sim.r

**Comment by hhollandmoritz** [comment]
I did this, I'm not sure it helped all that much. You can see the change here: https://github.com/hhollandmoritz/NWT_CLM/pull/2/commits/16c49595d618dfc95f43a97e984b129a3bbd5b9c

Sensible heat looks better but net radiation is still weird.

![flux_comp_plot_DM](https://user-images.githubusercontent.com/7916220/93861386-a6eec980-fc7d-11ea-8d0d-55850511b5fd.png)

**Comment by wwieder** [comment]
These look OK now, after using correct options in user_nl_datm
